# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiuvY-F-uEksMiMc9X54q7lRib7LWAf-
"""

import yfinance as yf
import pandas as pd


def YahooData2returns(YahooData):
    try:
        adj_close = YahooData['Adj Close']
        price_array = adj_close.values
        lagged_returns = price_array[1:] / price_array[:-1] - 1
        return lagged_returns
    except KeyError:
        print("The 'Adj Close' column was not found in the data. Please check the data structure.")
        return None


def get_stock_data(symbol, start_date, end_date):
    try:
        data = yf.download(symbol, start=start_date, end=end_date)
        if data.empty:
            print(f"No data was retrieved for symbol {symbol} between {start_date} and {end_date}.")
        return data
    except Exception as e:
        print(f"An error occurred while downloading data: {e}")
        return None


if __name__ == "__main__":
    symbol = 'GS'
    start_date = '2020-01-01'
    end_date = '2023-12-31'
    data = get_stock_data(symbol, start_date, end_date)
    if data is not None:
        returns = YahooData2returns(data)
        if returns is not None:
            print(returns)
            data.to_csv(f'{symbol}_historical_data.csv')
            pd.Series(returns).to_csv(f'{symbol}_returns.csv', index=False)
